#***FOR MASTER and STORAGE***
#Please fill master/store.host with public IP, domain
#or 127.0.0.1 (only for local test)
[master]
host="127.0.0.1"
port=8080
#replicas number, there must be NOT LESS storage servers than replicas
replica=2
[store]
host="127.0.0.1"
port=9090
dir="_storage_9090"
[cache]
#Number of keys to track frequency.
num_counters=100000
#Maximum cost of cache.
max_cost=1073741824 #1G
#Number of keys per Get buffer.
buffer_items=64
