[general]
password="password" #used for storage heartbeat authentication
replica=2 #replicas number, there must be NOT LESS storage servers than replicas

#***FOR MASTER and STORAGE***
#Please fill master/store.host with public IP
#or 127.0.0.1 (only for local test)
[master]
host="127.0.0.1"
port=8080
[store]
host="127.0.0.1"
port=9090
dir="_storage_9090"

#[redis]
#url="localhost:6379"
#password=""
#db=0