#please fill master/store.host with public IP
#(if use cluster with multiple ips)
#or 127.0.0.1 (both master and storage are local)
[master]
host="127.0.0.1"
port=8080
[store]
host="127.0.0.1"
port=9090
dir="_storage_"

#[redis]
#url="localhost:6379"
#password=""
#db=0