// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: protobuf/storage.proto

package storage_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatVolumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId uint64 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
}

func (x *CreatVolumeRequest) Reset() {
	*x = CreatVolumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatVolumeRequest) ProtoMessage() {}

func (x *CreatVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreatVolumeRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CreatVolumeRequest) GetVolumeId() uint64 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

type CreatVolumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatVolumeResponse) Reset() {
	*x = CreatVolumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatVolumeResponse) ProtoMessage() {}

func (x *CreatVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreatVolumeResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{1}
}

type WriteNeedleBlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId   uint64 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NeedleId   uint64 `protobuf:"varint,2,opt,name=needle_id,json=needleId,proto3" json:"needle_id,omitempty"`
	FileExt    string `protobuf:"bytes,3,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`
	NeedleData []byte `protobuf:"bytes,4,opt,name=needle_data,json=needleData,proto3" json:"needle_data,omitempty"`
}

func (x *WriteNeedleBlobRequest) Reset() {
	*x = WriteNeedleBlobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteNeedleBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNeedleBlobRequest) ProtoMessage() {}

func (x *WriteNeedleBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNeedleBlobRequest.ProtoReflect.Descriptor instead.
func (*WriteNeedleBlobRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{2}
}

func (x *WriteNeedleBlobRequest) GetVolumeId() uint64 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *WriteNeedleBlobRequest) GetNeedleId() uint64 {
	if x != nil {
		return x.NeedleId
	}
	return 0
}

func (x *WriteNeedleBlobRequest) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *WriteNeedleBlobRequest) GetNeedleData() []byte {
	if x != nil {
		return x.NeedleData
	}
	return nil
}

type WriteNeedleBlobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WriteNeedleBlobResponse) Reset() {
	*x = WriteNeedleBlobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteNeedleBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNeedleBlobResponse) ProtoMessage() {}

func (x *WriteNeedleBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNeedleBlobResponse.ProtoReflect.Descriptor instead.
func (*WriteNeedleBlobResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{3}
}

type DeleteNeedleBlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId uint64 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NeedleId uint64 `protobuf:"varint,2,opt,name=needle_id,json=needleId,proto3" json:"needle_id,omitempty"`
}

func (x *DeleteNeedleBlobRequest) Reset() {
	*x = DeleteNeedleBlobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNeedleBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNeedleBlobRequest) ProtoMessage() {}

func (x *DeleteNeedleBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNeedleBlobRequest.ProtoReflect.Descriptor instead.
func (*DeleteNeedleBlobRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteNeedleBlobRequest) GetVolumeId() uint64 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *DeleteNeedleBlobRequest) GetNeedleId() uint64 {
	if x != nil {
		return x.NeedleId
	}
	return 0
}

type DeleteNeedleBlobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNeedleBlobResponse) Reset() {
	*x = DeleteNeedleBlobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNeedleBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNeedleBlobResponse) ProtoMessage() {}

func (x *DeleteNeedleBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNeedleBlobResponse.ProtoReflect.Descriptor instead.
func (*DeleteNeedleBlobResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{5}
}

var File_protobuf_storage_proto protoreflect.FileDescriptor

var file_protobuf_storage_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x22, 0x31, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x16,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6e,
	0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x19, 0x0a, 0x17,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x89, 0x02, 0x0a, 0x07, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x56, 0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65,
	0x42, 0x6c, 0x6f, 0x62, 0x12, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x20, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65,
	0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_storage_proto_rawDescOnce sync.Once
	file_protobuf_storage_proto_rawDescData = file_protobuf_storage_proto_rawDesc
)

func file_protobuf_storage_proto_rawDescGZIP() []byte {
	file_protobuf_storage_proto_rawDescOnce.Do(func() {
		file_protobuf_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_storage_proto_rawDescData)
	})
	return file_protobuf_storage_proto_rawDescData
}

var file_protobuf_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_storage_proto_goTypes = []interface{}{
	(*CreatVolumeRequest)(nil),       // 0: storage.CreatVolumeRequest
	(*CreatVolumeResponse)(nil),      // 1: storage.CreatVolumeResponse
	(*WriteNeedleBlobRequest)(nil),   // 2: storage.WriteNeedleBlobRequest
	(*WriteNeedleBlobResponse)(nil),  // 3: storage.WriteNeedleBlobResponse
	(*DeleteNeedleBlobRequest)(nil),  // 4: storage.DeleteNeedleBlobRequest
	(*DeleteNeedleBlobResponse)(nil), // 5: storage.DeleteNeedleBlobResponse
}
var file_protobuf_storage_proto_depIdxs = []int32{
	0, // 0: storage.Storage.CreateVolume:input_type -> storage.CreatVolumeRequest
	2, // 1: storage.Storage.WriteNeedleBlob:input_type -> storage.WriteNeedleBlobRequest
	4, // 2: storage.Storage.DeleteNeedleBlob:input_type -> storage.DeleteNeedleBlobRequest
	1, // 3: storage.Storage.CreateVolume:output_type -> storage.CreatVolumeResponse
	3, // 4: storage.Storage.WriteNeedleBlob:output_type -> storage.WriteNeedleBlobResponse
	5, // 5: storage.Storage.DeleteNeedleBlob:output_type -> storage.DeleteNeedleBlobResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_storage_proto_init() }
func file_protobuf_storage_proto_init() {
	if File_protobuf_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatVolumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatVolumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteNeedleBlobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteNeedleBlobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNeedleBlobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNeedleBlobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_storage_proto_goTypes,
		DependencyIndexes: file_protobuf_storage_proto_depIdxs,
		MessageInfos:      file_protobuf_storage_proto_msgTypes,
	}.Build()
	File_protobuf_storage_proto = out.File
	file_protobuf_storage_proto_rawDesc = nil
	file_protobuf_storage_proto_goTypes = nil
	file_protobuf_storage_proto_depIdxs = nil
}
