// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: protobuf/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_success Status = 0
	Status_failure Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "success",
		1: "failure",
	}
	Status_value = map[string]int32{
		"success": 0,
		"failure": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_storage_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protobuf_storage_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{0}
}

type CreatVolumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatVolumeRequest) Reset() {
	*x = CreatVolumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatVolumeRequest) ProtoMessage() {}

func (x *CreatVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreatVolumeRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CreatVolumeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreatVolumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Status `protobuf:"varint,1,opt,name=code,proto3,enum=Status" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreatVolumeResponse) Reset() {
	*x = CreatVolumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatVolumeResponse) ProtoMessage() {}

func (x *CreatVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreatVolumeResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{1}
}

func (x *CreatVolumeResponse) GetCode() Status {
	if x != nil {
		return x.Code
	}
	return Status_success
}

func (x *CreatVolumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadNeedleBlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId uint64 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NeedleId uint64 `protobuf:"varint,2,opt,name=needle_id,json=needleId,proto3" json:"needle_id,omitempty"`
}

func (x *ReadNeedleBlobRequest) Reset() {
	*x = ReadNeedleBlobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNeedleBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNeedleBlobRequest) ProtoMessage() {}

func (x *ReadNeedleBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNeedleBlobRequest.ProtoReflect.Descriptor instead.
func (*ReadNeedleBlobRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ReadNeedleBlobRequest) GetVolumeId() uint64 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *ReadNeedleBlobRequest) GetNeedleId() uint64 {
	if x != nil {
		return x.NeedleId
	}
	return 0
}

type ReadNeedleBlobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeedleChunk []byte `protobuf:"bytes,1,opt,name=needle_chunk,json=needleChunk,proto3" json:"needle_chunk,omitempty"`
}

func (x *ReadNeedleBlobResponse) Reset() {
	*x = ReadNeedleBlobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNeedleBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNeedleBlobResponse) ProtoMessage() {}

func (x *ReadNeedleBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNeedleBlobResponse.ProtoReflect.Descriptor instead.
func (*ReadNeedleBlobResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ReadNeedleBlobResponse) GetNeedleChunk() []byte {
	if x != nil {
		return x.NeedleChunk
	}
	return nil
}

type WriteNeedleBlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId    uint64 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NeedleId    uint64 `protobuf:"varint,2,opt,name=needle_id,json=needleId,proto3" json:"needle_id,omitempty"`
	NeedleChunk []byte `protobuf:"bytes,3,opt,name=needle_chunk,json=needleChunk,proto3" json:"needle_chunk,omitempty"`
}

func (x *WriteNeedleBlobRequest) Reset() {
	*x = WriteNeedleBlobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteNeedleBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNeedleBlobRequest) ProtoMessage() {}

func (x *WriteNeedleBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNeedleBlobRequest.ProtoReflect.Descriptor instead.
func (*WriteNeedleBlobRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{4}
}

func (x *WriteNeedleBlobRequest) GetVolumeId() uint64 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *WriteNeedleBlobRequest) GetNeedleId() uint64 {
	if x != nil {
		return x.NeedleId
	}
	return 0
}

func (x *WriteNeedleBlobRequest) GetNeedleChunk() []byte {
	if x != nil {
		return x.NeedleChunk
	}
	return nil
}

type WriteNeedleBlobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Status `protobuf:"varint,1,opt,name=code,proto3,enum=Status" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WriteNeedleBlobResponse) Reset() {
	*x = WriteNeedleBlobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteNeedleBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteNeedleBlobResponse) ProtoMessage() {}

func (x *WriteNeedleBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteNeedleBlobResponse.ProtoReflect.Descriptor instead.
func (*WriteNeedleBlobResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{5}
}

func (x *WriteNeedleBlobResponse) GetCode() Status {
	if x != nil {
		return x.Code
	}
	return Status_success
}

func (x *WriteNeedleBlobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteNeedleBlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeId uint64 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NeedleId uint64 `protobuf:"varint,2,opt,name=needle_id,json=needleId,proto3" json:"needle_id,omitempty"`
}

func (x *DeleteNeedleBlobRequest) Reset() {
	*x = DeleteNeedleBlobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNeedleBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNeedleBlobRequest) ProtoMessage() {}

func (x *DeleteNeedleBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNeedleBlobRequest.ProtoReflect.Descriptor instead.
func (*DeleteNeedleBlobRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNeedleBlobRequest) GetVolumeId() uint64 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *DeleteNeedleBlobRequest) GetNeedleId() uint64 {
	if x != nil {
		return x.NeedleId
	}
	return 0
}

type DeleteNeedleBlobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Status `protobuf:"varint,1,opt,name=code,proto3,enum=Status" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteNeedleBlobResponse) Reset() {
	*x = DeleteNeedleBlobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNeedleBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNeedleBlobResponse) ProtoMessage() {}

func (x *DeleteNeedleBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNeedleBlobResponse.ProtoReflect.Descriptor instead.
func (*DeleteNeedleBlobResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_storage_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNeedleBlobResponse) GetCode() Status {
	if x != nil {
		return x.Code
	}
	return Status_success
}

func (x *DeleteNeedleBlobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobuf_storage_proto protoreflect.FileDescriptor

var file_protobuf_storage_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x15,
	0x52, 0x65, 0x61, 0x64, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x3b, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x65,
	0x64, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x75, 0x0a, 0x16,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x22, 0x50, 0x0a, 0x17, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64,
	0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x18, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x22, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10,
	0x01, 0x32, 0xa1, 0x02, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0e, 0x52, 0x65, 0x61,
	0x64, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x16, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65,
	0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x48, 0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42,
	0x6c, 0x6f, 0x62, 0x12, 0x17, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c,
	0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x49, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x18,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_storage_proto_rawDescOnce sync.Once
	file_protobuf_storage_proto_rawDescData = file_protobuf_storage_proto_rawDesc
)

func file_protobuf_storage_proto_rawDescGZIP() []byte {
	file_protobuf_storage_proto_rawDescOnce.Do(func() {
		file_protobuf_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_storage_proto_rawDescData)
	})
	return file_protobuf_storage_proto_rawDescData
}

var file_protobuf_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protobuf_storage_proto_goTypes = []interface{}{
	(Status)(0),                      // 0: status
	(*CreatVolumeRequest)(nil),       // 1: CreatVolumeRequest
	(*CreatVolumeResponse)(nil),      // 2: CreatVolumeResponse
	(*ReadNeedleBlobRequest)(nil),    // 3: ReadNeedleBlobRequest
	(*ReadNeedleBlobResponse)(nil),   // 4: ReadNeedleBlobResponse
	(*WriteNeedleBlobRequest)(nil),   // 5: WriteNeedleBlobRequest
	(*WriteNeedleBlobResponse)(nil),  // 6: WriteNeedleBlobResponse
	(*DeleteNeedleBlobRequest)(nil),  // 7: DeleteNeedleBlobRequest
	(*DeleteNeedleBlobResponse)(nil), // 8: DeleteNeedleBlobResponse
}
var file_protobuf_storage_proto_depIdxs = []int32{
	0, // 0: CreatVolumeResponse.code:type_name -> status
	0, // 1: WriteNeedleBlobResponse.code:type_name -> status
	0, // 2: DeleteNeedleBlobResponse.code:type_name -> status
	1, // 3: Storage.CreatVolume:input_type -> CreatVolumeRequest
	3, // 4: Storage.ReadNeedleBlob:input_type -> ReadNeedleBlobRequest
	5, // 5: Storage.WriteNeedleBlob:input_type -> WriteNeedleBlobRequest
	7, // 6: Storage.DeleteNeedleBlob:input_type -> DeleteNeedleBlobRequest
	2, // 7: Storage.CreatVolume:output_type -> CreatVolumeResponse
	4, // 8: Storage.ReadNeedleBlob:output_type -> ReadNeedleBlobResponse
	6, // 9: Storage.WriteNeedleBlob:output_type -> WriteNeedleBlobResponse
	8, // 10: Storage.DeleteNeedleBlob:output_type -> DeleteNeedleBlobResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_storage_proto_init() }
func file_protobuf_storage_proto_init() {
	if File_protobuf_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatVolumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatVolumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNeedleBlobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNeedleBlobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteNeedleBlobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteNeedleBlobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNeedleBlobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNeedleBlobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_storage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_storage_proto_goTypes,
		DependencyIndexes: file_protobuf_storage_proto_depIdxs,
		EnumInfos:         file_protobuf_storage_proto_enumTypes,
		MessageInfos:      file_protobuf_storage_proto_msgTypes,
	}.Build()
	File_protobuf_storage_proto = out.File
	file_protobuf_storage_proto_rawDesc = nil
	file_protobuf_storage_proto_goTypes = nil
	file_protobuf_storage_proto_depIdxs = nil
}
