// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: protobuf/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	CreatVolume(ctx context.Context, in *CreatVolumeRequest, opts ...grpc.CallOption) (*CreatVolumeResponse, error)
	ReadNeedleBlob(ctx context.Context, in *ReadNeedleBlobRequest, opts ...grpc.CallOption) (Storage_ReadNeedleBlobClient, error)
	WriteNeedleBlob(ctx context.Context, opts ...grpc.CallOption) (Storage_WriteNeedleBlobClient, error)
	DeleteNeedleBlob(ctx context.Context, in *DeleteNeedleBlobRequest, opts ...grpc.CallOption) (*DeleteNeedleBlobResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) CreatVolume(ctx context.Context, in *CreatVolumeRequest, opts ...grpc.CallOption) (*CreatVolumeResponse, error) {
	out := new(CreatVolumeResponse)
	err := c.cc.Invoke(ctx, "/Storage/CreatVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ReadNeedleBlob(ctx context.Context, in *ReadNeedleBlobRequest, opts ...grpc.CallOption) (Storage_ReadNeedleBlobClient, error) {
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[0], "/Storage/ReadNeedleBlob", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageReadNeedleBlobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_ReadNeedleBlobClient interface {
	Recv() (*ReadNeedleBlobResponse, error)
	grpc.ClientStream
}

type storageReadNeedleBlobClient struct {
	grpc.ClientStream
}

func (x *storageReadNeedleBlobClient) Recv() (*ReadNeedleBlobResponse, error) {
	m := new(ReadNeedleBlobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) WriteNeedleBlob(ctx context.Context, opts ...grpc.CallOption) (Storage_WriteNeedleBlobClient, error) {
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[1], "/Storage/WriteNeedleBlob", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageWriteNeedleBlobClient{stream}
	return x, nil
}

type Storage_WriteNeedleBlobClient interface {
	Send(*WriteNeedleBlobRequest) error
	CloseAndRecv() (*WriteNeedleBlobResponse, error)
	grpc.ClientStream
}

type storageWriteNeedleBlobClient struct {
	grpc.ClientStream
}

func (x *storageWriteNeedleBlobClient) Send(m *WriteNeedleBlobRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageWriteNeedleBlobClient) CloseAndRecv() (*WriteNeedleBlobResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteNeedleBlobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) DeleteNeedleBlob(ctx context.Context, in *DeleteNeedleBlobRequest, opts ...grpc.CallOption) (*DeleteNeedleBlobResponse, error) {
	out := new(DeleteNeedleBlobResponse)
	err := c.cc.Invoke(ctx, "/Storage/DeleteNeedleBlob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	CreatVolume(context.Context, *CreatVolumeRequest) (*CreatVolumeResponse, error)
	ReadNeedleBlob(*ReadNeedleBlobRequest, Storage_ReadNeedleBlobServer) error
	WriteNeedleBlob(Storage_WriteNeedleBlobServer) error
	DeleteNeedleBlob(context.Context, *DeleteNeedleBlobRequest) (*DeleteNeedleBlobResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) CreatVolume(context.Context, *CreatVolumeRequest) (*CreatVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatVolume not implemented")
}
func (UnimplementedStorageServer) ReadNeedleBlob(*ReadNeedleBlobRequest, Storage_ReadNeedleBlobServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadNeedleBlob not implemented")
}
func (UnimplementedStorageServer) WriteNeedleBlob(Storage_WriteNeedleBlobServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteNeedleBlob not implemented")
}
func (UnimplementedStorageServer) DeleteNeedleBlob(context.Context, *DeleteNeedleBlobRequest) (*DeleteNeedleBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNeedleBlob not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_CreatVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreatVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/CreatVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreatVolume(ctx, req.(*CreatVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ReadNeedleBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadNeedleBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).ReadNeedleBlob(m, &storageReadNeedleBlobServer{stream})
}

type Storage_ReadNeedleBlobServer interface {
	Send(*ReadNeedleBlobResponse) error
	grpc.ServerStream
}

type storageReadNeedleBlobServer struct {
	grpc.ServerStream
}

func (x *storageReadNeedleBlobServer) Send(m *ReadNeedleBlobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_WriteNeedleBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).WriteNeedleBlob(&storageWriteNeedleBlobServer{stream})
}

type Storage_WriteNeedleBlobServer interface {
	SendAndClose(*WriteNeedleBlobResponse) error
	Recv() (*WriteNeedleBlobRequest, error)
	grpc.ServerStream
}

type storageWriteNeedleBlobServer struct {
	grpc.ServerStream
}

func (x *storageWriteNeedleBlobServer) SendAndClose(m *WriteNeedleBlobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageWriteNeedleBlobServer) Recv() (*WriteNeedleBlobRequest, error) {
	m := new(WriteNeedleBlobRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Storage_DeleteNeedleBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNeedleBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteNeedleBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/DeleteNeedleBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteNeedleBlob(ctx, req.(*DeleteNeedleBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatVolume",
			Handler:    _Storage_CreatVolume_Handler,
		},
		{
			MethodName: "DeleteNeedleBlob",
			Handler:    _Storage_DeleteNeedleBlob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadNeedleBlob",
			Handler:       _Storage_ReadNeedleBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteNeedleBlob",
			Handler:       _Storage_WriteNeedleBlob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/storage.proto",
}
